version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: cd bulletin-board && npm i
      - run: cd bulletin-board && npm i eslint eslint-config-google
      - run: cd bulletin-board && npx eslint -c ../.eslintrc.json .
